name: Auto-Close PRs

on:
  pull_request_target:
    types:
      - opened

permissions:
    pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
    - uses: dessant/repo-lockdown@6e7465417db1c79a9c02df1797672f2bca97c926 # v4.0.0
      with:
        github-token: ${{ github.token }}
        process-only: prs
        pr-comment: >-
          This is an issues-only repository. **Public pull requests are not accepted.**